### PR TITLE
feat: elliptic curve base64 signature support and bug fixes

### PR DESCRIPTION
**Pull request by kabaluyot**
Fixes the ff:
- follow latest ec pem openssh standard .. See https://wiki.openssl.org/index.php/Command_Line_Elliptic_Curve_Operations

Added the ff:
- support other curves for encoding public key to pem
- support for signing and verifying signature in base64 format
- add elliptic curve crypto example

### CODE REVIEW

**Comment by kabaluyot** [comment]
Fixes https://github.com/Ephenodrom/Dart-Basic-Utils/issues/57

**Comment by Ephenodrom** [comment]
@kabaluyot 
Thank you for the PR. This looks very good. Can you please add a few tests for this ? If this is done i will merge the PR and create a new release on pub.dev.

**Comment by Ephenodrom** [comment]
@kabaluyot Any news on the tests ?

**Comment by kabaluyot** [comment]
I will try to add today. Sorry was very busy in the past days

**Comment by kabaluyot** [comment]
Blocked by https://github.com/Ephenodrom/Dart-Basic-Utils/issues/67

**Pull request closed without merging**
