### PR TITLE
Fixing error Error: The argument type 'String' can't be assigned to t…

### PR DESCRIPTION
**Pull request by MedwinCorreo**
…he parameter type 'Uri'.

 Error: The argument type 'String' can't be assigned to the parameter type 'Uri'.
 
image

### CODE REVIEW

**Review by rwrz — APPROVED** [review]
All good to me!

**Comment by Ephenodrom** [comment]
This should not be necessary, since everytime before the client.get() is called, the code runs through this method:
```dart
static Uri _getUriUrl(
      String url, Map<String, dynamic>? queryParameters) {
    if (queryParameters == null || queryParameters.isEmpty) return Uri.parse(url);
    return Uri.parse(url).replace(queryParameters: queryParameters);
  }
```
Therefore the string is in everycase parsed as an URI object. Is your code up to date and do you use the latest version of the package ?

@MedwinCorreo / @rwrz

**Comment by rwrz** [comment]
Yeah. I just realize that... sorry about reviewing it wrongly.

**Comment by Ephenodrom** [comment]
The PR will be closed. Alread fixed in the latest Version.

**Pull request closed without merging**
